Encoder working and form is no longer empty.
spknetwork/3Speak-app pull request #33
Opened 2022-11-14 18:00 UTC by igormuba

Now the formdata is no longer empty and the title, description and tags can be used to post.

2022-11-15 04:42 UTC, vaultec81 commented on src/renderer/views/UploaderView.tsx
> +  const [publishForm, setPublishForm] = useState({ title: '', description: '', tags: '' })
I'd probably use individual useState() instead of one big object. Just makes it a bit more complicated when you have multiple things stuffed in one object

2022-11-15 13:41 UTC, igormuba commented on src/renderer/views/UploaderView.tsx
> +  const [publishForm, setPublishForm] = useState({ title: '', description: '', tags: '' })
@vaultec81 made the change on a new commit on this PR 
https://github.com/spknetwork/3Speak-app/pull/33/commits/380b06625494d1a3c2c1c7c5435bcac80f5be981

2022-11-16 22:47 UTC, vaultec81 requested changes
See comments

2022-11-16 22:47 UTC, vaultec81 commented on src/renderer/views/UploaderView.tsx
> +                  onChange={(e) => setPublishForm({ ...publishForm, title: e.target.value })}
setPublishForm undefined?

2022-11-16 22:47 UTC, vaultec81 commented on src/renderer/views/UploaderView.tsx
> +          title: publishFormTitle || 'no form data',
I'd suggest leaving the description to an empty string, and title to a proper place holder. Like the file name of the video or "Unnamed video"

2022-11-17 17:22 UTC, igormuba commented on src/renderer/views/UploaderView.tsx
> +                  onChange={(e) => setPublishForm({ ...publishForm, title: e.target.value })}
Fixed. It was a mistake, now we are properly using one different state for title, description and tags, differently from the old way of using one object ref for everything

2022-11-18 06:33 UTC, merged